env:
  global:
    secure: lZ5JLHVz0upj4a18YRCy0pxcchFzYBWFxGD6CoIqBhiZNgR5KpLQrkji+RJVq7hAvgKXbq69C8icJF3hjTV0wkyeEP/eVYYSW+60MkFJWv+BZs1ZOS2v+oMNo+Alv9lfpixf1A4pDAHSLTWG2/omCvKUJFCLbz7zooe2f2bjOKBPmdhb3A5ghisSone+bCFCujzguCTG0URbdaGcBR0BfIukwakevWUGvBNSX3Cg6LRMiwYBPv+dgmfVhZzFxqIky8xffpaWjoFNLFPldzjQpiJ/98YDwQ6Z4Gf3HzEDNMvfgoGNxCJEGh7a654aNeeDMZWZY3/RKUTPonm//iSO2uZi0E45Hgho1B65edvzRHxLwCnfEV6Mqh2jo0s5KH8sg0onZs0XnbCJeUr2cMyqlMQgHkRlc652IJ0dMYViMCnwQ0eLEFVFb6rKfqqyY9Mgq8mp168Hdmo95Vj6Xun5h6EhgKs8BRiuoVN9EtCcnNJb41gDqAZmR8pZT8ltiqtj0tZT2TdPxCG+EODbaoDC/bBaM92XpI6VK+iNGVC9F48uGwTn5ear6jBr6gMTHbZI/48tpWPnaCSX+uJbWg5Vyn0Zr2+vFRsmmcJ4s6DtkCnWf0TgoFEVLarAXGYZYIhw4S7vlTt9n3FgAotGRud3heI61+JvkU16AcrTPN9zE3E=

before_install:
  - travis_retry wget -q -O- https://s3.amazonaws.com/download.fpcomplete.com/ubuntu/fpco.key | sudo apt-key add -
  - travis_retry echo 'deb http://download.fpcomplete.com/ubuntu/precise stable main'|sudo tee /etc/apt/sources.list.d/fpco.list
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install stack -y

install:
  - stack --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - stack setup

script:
  - stack build && stack test